Backend vehicle crud
ubclaunchpad/microvan pull request #12
Opened 2023-11-05 05:12 UTC by kevinrczhang

# Description

Please include a summary of the change and which issue is fixed. Add any screenshots of the change.

Fixes # (ticket #)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-11-06 17:34 UTC, ltan02 requested changes

2023-11-06 17:34 UTC, ltan02 commented on requirements.txt
@kevinrczhang Could we remove this file?

2023-11-07 19:03 UTC, kevinrczhang commented on requirements.txt
I was using that to save all the project dependencies on my machine, assuming we'd go with venv instead. Are we going to just stick with pipenv?

2023-11-07 23:04 UTC, ltan02 commented on requirements.txt
@kevinrczhang We'll stick to pipenv and I can help set things up for you during our meeting tomorrow.

2023-11-08 01:50 UTC, ltan02 approved these changes

2023-11-08 01:55 UTC, merged